# Generated by Django 6.1.1 on 2026-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=50)),
                ('certificate_url', models.URLField(blank=True)),
            ],
        ),
    ]
